### ISSUE TITLE
evaluation config/code release

### ISSUE THREAD

**Issue by wren93** [KangarooGroup/Kangaroo#7]
Hi, thanks for this great work. I was wondering if you are planning to release the evaluation configurations or evaluation scripts for Kangaroo? I got ~59% accuracy on MVBench, which is a bit lower than the scores reported in the paper. Could you share the configurations for evaluating on these datasets? Thanks

**Comment by IceWYB** [comment]
To keep it consistent with the training process, we use templates for multi-choice QA pairs during evaluation. The complete evaluation code will be released in next versions
